RequireFiles("Shared/Utils/", {
    "String",
    "Loca",
    "Message",
    "File",
    "Log",
    "Character",
    "Database",
    "Entity",
    "Inventory",
    "Item",
    "Math",
    "ModVars",
    "Object",
    "Table",
    "Template",
    "Timer",
    "Treasure",
    "ActionResource",
    "MessageBox",
    "Net"
    --"ClientUI"
})
